name: CI/CD Databricks

on:
  push:
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python & deps
        run: |
          pip install -r requirements-dev.txt

      - name: Run unit tests
        run: pytest -q

      - name: Deploy job to Databricks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks jobs update \
            --job-id <job_id> \
            --json @conf/job_weather_pipeline.json
